### ISSUE TITLE
Suggestion: Dark Mode

### ISSUE THREAD

**Issue by Chizaruu** [TStand90/roguelike-tutorials-website#34]
My eyes burn in the light.

**Comment by HexDecimal** [comment]
Some info in implementing dark mode: https://css-tricks.com/dark-modes-with-css/

**Comment by Chizaruu** [comment]
I've attempted to use Hugo to build a test site as I wanted to make sure my code works before contributing; however, I've run into RSSLink issues when building. 

`Error: Error building site: failed to render pages: render of "page" failed: "B:\GitHub\Roguelike\roguelike-tutorials-website\themes\bootstrap\layouts\_default\baseof.html:18:10": execute of template failed: template: _default/single.html:18:10: executing "_default/single.html" at <.RSSLink>: can't evaluate field RSSLink in type *hugolib.pageState
Built in 132 ms
`

I believe this to be due to depreciation.  #https://github.com/Xzya/hugo-bootstrap/issues/38

Commands used: 

`hugo serve`
`hugo -minify`

P.S This is my first time dabbling with Hugo.

**Comment by Chizaruu** [comment]
My quest to create a dev environment to test my dark mode support led me on a journey.

1. I added specific .RelPermalink support to #https://github.com/Xzya/hugo-bootstrap/pull/39. This change allows the latest stable version of Hugo (currently v0.102.3-b) to build **this** site successfully.
   - My Fork: [Chizaruu/hugo-bootstrap](https://github.com/Chizaruu/hugo-bootstrap)
2. I implemented a workflow allowing for automatic redeployments with every commit using Github Pages 
   - @TStand90, I'll open a PR for it if you would like to make use of it :)
   - Website Fork - https://chizaruu.github.io/roguelike-tutorials-website/
   ![image](https://user-images.githubusercontent.com/59434446/190421991-e4ca782d-b0ed-49b8-9a68-31bd5664bbe3.png)
3. It's a pain to directly manipulate the code in Hugo-bootstrap as it uses code from [alanorth/hugo-theme-bootstrap4-blog](https://github.com/alanorth/hugo-theme-bootstrap4-blog) and to counter the fact that I don't want to deal with the immediate problems, I'll look towards implementing a quick fix in the form of [DarkReader](https://darkreader.org/) on my [hugo-bootstrap](https://github.com/Chizaruu/hugo-bootstrap) fork.

**Comment by TStand90** [comment]
Update on this:

First, the site has been redeployed with a new theme ([Coder](https://github.com/luizdepra/hugo-coder)). It comes in dark mode by default, but is toggleable for those who prefer light mode.

This is something I've meant to do for awhile now. The bootstrap theme was one I picked out of convenience rather than because I liked it. At the time, I tried several different themes and ended up picking this one because it needed the least amount of configuration.

There's still some weirdness going on due to the theme change, like the home page having no text and the tutorial index pages displaying posts as if they were from a blog, but the main parts of the site work, so I'll leave it there for now for the sake of my sanity.

Second, as you noticed, the PR was merged but doesn't yet work. I will try to get the auto-redeploys running soon. I would have done that today, but updating the theme ended up taking far more time than I would have ever anticipated, mostly because of having to update Hugo several versions, fiddling with the themes, and some other weird annoyances.

Thanks for your patience on this one. I know there's no good reason to have ignored these comments and the PR for six months, so I sincerely apologize for that. I'm currently working on a blog post that will explain of my lack of updates (to some extent), which should be posted in the near future.

**Comment by Chizaruu** [comment]
After the PR was merged, I commented on the instructions to set up the auto-deployment. :)
https://github.com/TStand90/roguelike-tutorials-website/pull/35#issuecomment-1407559351

Otherwise, the issue has been handled due to the dark mode being supported.  e8eb3637606ef915484c68d7ce07ca210c6367ed

I'll see if I can help you get your text back and resolve the blog-like issue.
